/**
 * domain/agent.ts — agent-usage telemetry domain module (§5.1).
 *
 * Replaces onAgentUsage from telemetry-hooks.ts. Emits OTel-standard metrics
 * for token usage, cost, cache efficiency, and operation duration.
 *
 * Cardinality fix (§7.8): high-cardinality identifiers (task_id, graph_id,
 * prefix_hash) are pushed onto the active span only — never into metric labels.
 *
 * Fire-and-forget: synchronous API, never throws to caller.
 */

import { getMeter } from '../core.js';
import { METRIC, ATTR } from '../schema.js';
import type { GenAiOperationName } from '../schema.js';
import { logger } from '../../logger.js';
import { getCacheAnomalyDetector } from './anomaly.js';

// Pre-load @opentelemetry/api so trace.getActiveSpan() is available when
// onAgentUsage() is called (WSL cold-start workaround — same pattern as core.ts).
let _trace: typeof import('@opentelemetry/api').trace | null = null;
import('@opentelemetry/api')
  .then((api) => { _trace = api.trace; })
  .catch(() => {});

// ── Event type ────────────────────────────────────────────────────────────────

/**
 * Matches the combined shape of attrs + usage from the legacy onAgentUsage
 * signature in telemetry-hooks.ts — flattened into a single event object.
 */
export interface AgentUsageEvent {
  /** Agent role (e.g. "coder", "orchestrator"). Low-cardinality metric label. */
  role: string;
  /** Model identifier (e.g. "claude-sonnet-4-6"). */
  model: string;
  /** Graph identifier — high cardinality, span attribute only. */
  graphId: string;
  /** Task identifier — high cardinality, span attribute only. */
  taskId: string;
  /** Bureau project name. */
  project: string;
  /** Cache prefix hash — high cardinality, span attribute only. */
  prefixHash?: string;
  /** Uncached input tokens. */
  inputTokens: number;
  /** Output tokens. */
  outputTokens: number;
  /** Cache read tokens (existing cache hit). */
  cacheReadInputTokens: number;
  /** Cache creation tokens (new cache write). */
  cacheCreationInputTokens: number;
  /** Total cost for this invocation in USD. */
  totalCostUsd: number;
  /** Wall-clock duration in milliseconds. */
  durationMs: number;
  /** Error classifier — set on failure only. Omit on success (do not emit error.type="none"). */
  errorType?: string;
  /** Toolchain identifier (e.g. "node", "python", "dotnet"). Low-cardinality. Optional — absent when not dispatched via toolchain registry. */
  toolchain?: string;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Record agent usage metrics. Synchronous, fire-and-forget. Never throws.
 *
 * Replaces telemetry-hooks.ts onAgentUsage (§5.1).
 */
export function onAgentUsage(event: AgentUsageEvent): void {
  try {
    _emitAgentUsage(event);
  } catch (err) {
    logger.warn({ err: String(err) }, 'agent domain: onAgentUsage failed — swallowed');
  }
}

// ── Internal emission ─────────────────────────────────────────────────────────

function _emitAgentUsage(event: AgentUsageEvent): void {
  const m = getMeter();
  if (!m) return;

  // §7.8 cardinality fix: high-cardinality identifiers go on the active span,
  // never into metric attribute sets.
  const activeSpan = _trace?.getActiveSpan();
  if (activeSpan) {
    activeSpan.setAttribute(ATTR.TASK_ID, event.taskId);
    activeSpan.setAttribute(ATTR.GRAPH_ID, event.graphId);
    if (event.prefixHash !== undefined) {
      activeSpan.setAttribute(ATTR.AGENT_PREFIX_HASH, event.prefixHash);
    }
  }

  // Low-cardinality attribute set — safe as metric labels (§7.8).
  const operationName: GenAiOperationName = 'invoke_agent';
  const baseAttrs: Record<string, string> = {
    [ATTR.OPERATION_NAME]: operationName,
    [ATTR.PROVIDER_NAME]: 'anthropic',
    [ATTR.REQUEST_MODEL]: event.model,
    [ATTR.RESPONSE_MODEL]: event.model,
    [ATTR.ROLE]: event.role,
  };
  // error.type ONLY on failure — never emit error.type="none" on success.
  if (event.errorType !== undefined) {
    baseAttrs[ATTR.ERROR_TYPE] = event.errorType;
  }
  // toolchain is optional — omit when absent to keep the no-toolchain metric series clean.
  if (event.toolchain !== undefined) {
    baseAttrs[ATTR.TOOLCHAIN] = event.toolchain;
  }

  // gen_ai.client.token.usage — two records per OTel GenAI semconv:
  //   input  = sum of all tokens consumed from the input side (cached + uncached)
  //   output = tokens generated by the model
  const totalInput =
    event.inputTokens + event.cacheReadInputTokens + event.cacheCreationInputTokens;
  const tokenUsage = m.createHistogram(METRIC.TOKEN_USAGE, { unit: '{token}' });
  tokenUsage.record(totalInput, { ...baseAttrs, [ATTR.TOKEN_TYPE]: 'input' });
  tokenUsage.record(event.outputTokens, { ...baseAttrs, [ATTR.TOKEN_TYPE]: 'output' });

  // gen_ai.client.operation.duration — seconds per OTel GenAI semconv.
  m.createHistogram(METRIC.OPERATION_DURATION, { unit: 's' })
    .record(event.durationMs / 1000, baseAttrs);

  // bureau.agent.cost_usd — per-run cost distribution.
  m.createHistogram(METRIC.AGENT_COST_USD, { unit: 'USD' })
    .record(event.totalCostUsd, baseAttrs);

  // bureau.agent.cost_usd.total — monotonic running total counter.
  m.createCounter(METRIC.AGENT_COST_USD_TOTAL, { unit: 'USD' })
    .add(event.totalCostUsd, baseAttrs);

  // bureau.agent.cache_hit_rate — ratio of cache reads to total input tokens (0..1).
  const cacheHitRate = totalInput > 0 ? event.cacheReadInputTokens / totalInput : 0;
  m.createHistogram(METRIC.AGENT_CACHE_HIT_RATE, { unit: '1' })
    .record(cacheHitRate, baseAttrs);

  // Fire-and-forget anomaly observation. Never await; errors are silent.
  void getCacheAnomalyDetector()
    ?.observe(
      {
        role: event.role,
        model: event.model,
        graphId: event.graphId,
        taskId: event.taskId,
        toolchain: event.toolchain ?? 'node',
      },
      {
        inputTokens: event.inputTokens,
        outputTokens: event.outputTokens,
        cacheReadInputTokens: event.cacheReadInputTokens,
        cacheCreationInputTokens: event.cacheCreationInputTokens,
        totalCostUsd: event.totalCostUsd,
      },
      event.prefixHash ?? null,
    )
    .catch(() => {});
}
